#!/usr/bin/python3
def divisible_by_2(my_list=[]):
    boollist=[len(my_list) + 1]
    for i in range(len(my_list)):
        if my_list[i]  % 2 == 0:
            boollist[i] = True
        else:
            boollist[i] = False
